services:
    algo-distinct-solutions:
        build: ./AlgoDistinctSolutions
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities: [gpu]